const Rounds = {
  entrance: [
    "jV1czJpS",
    "3QckzyEP",
    "TD2joug5",
    "IZT6nnsQ",
    "EZEtF58I",
    "SJQrVn68",
    "dsuXTP2I",
    "7pWzPWo6",
    "18tQ5wtj",
    "AKacviZM",
    "s9lTiEV3",
    "pSzQ444x",
    "8beWBLM0",
    "Ye25tPWQ",
    "2Yzu9iDP",
    "RiTrF1CN",
    "YylmHdsj",
    "ySog9Nys",
    "6fIfBYSm",
    "bqYzJIz6",
    "KN8BqVPJ",
    "vsh6g1N5",
    "38hsvoJ7",
    "PUTGVsAo",
    "AyK6YLPa",
    "SZi5b154",
    "gAQ2D5mY",
    "hRhK1GdN",
    "fZStNTwy",
    "w2xZYuvC",
    "r2bYTN3y",
  ],
  league2: [
    "Ra9cvKwF",
    "0XUP8y4I",
    "YEpI0WCh",
    "HGHxMu47",
    "oybMrORH",
    "69XnCuuY",
    "GWhnBOJe",
    "0renldRa",
    "TRZq6FjW",
    "WX024rDc",
    "dEiWrlIz",
    "p0eosBnB",
    "5HTPZngh",
    "TWP31Vqf",
    "gBOnTgVS",
    "1tdL23SI",
    "oW3Jp7yt",
    "cFbhqFyJ",
    "iQxQy8vJ",
    "K4xbrB8e",
    "Q2tQ6x4I",
    "4goFRYKI",
    "qcAxBXkK",
    "9FsxUdsi",
    "i5gHNofs",
    "bNSldTPA",
    "JnItCy26",
    "r7v9ypzD",
    "Tzs2P4RG",
    "0gomzaI4",
    "EqYIYPjB",
    "JtjQnA1U",
    "BGRJ8u1i",
    "9yTu3Fbp",
    "snFW8QrQ",
    "o1PVTw90",
    "BEBzimzP",
    "BIA9NoEQ",
    "if3tEYmU",
    "PMrrXJYz",
    "GW5MOiLr",
    "idj1kKhy",
    "i4oH3xfk",
    "ynw42l4Y",
    "kpLX0Xba",
  ],
  league1: [
    "UNtPCSYm",
    "JqKkw2GQ",
    "YIJAoqRY",
    "PmetuSS3",
    "CJL3zjIt",
    "2sKiSO4S",
    "dag8n041",
    "sVt2s8Nw",
    "SMyHuCga",
    "BESSYHkn",
    "DkunSYis",
    "Bi5E91Qn",
    "8Y0LxOiz",
    "dLGeWHF2",
    "47LMnJix",
    "JUGdP4n3",
    "71rD1Ott",
    "CI0BTvGD",
    "SSNAkZnn",
    "zs387cMe",
    "sWUdGhWu",
    "zyBl0oI4",
    "0EmjbFGF",
    "R2VNWbgw",
    "c7YZVjQR",
    "i5Pp8dzI",
    "LZ57IOsu",
    "WSfVzRla",
    "WXM0CL0n",
    "c2YnzCxo",
    "NMtUn8kP",
    "im83IJ8E",
    "Ycg6ANGI",
    "EruKoxE8",
    "AGqhZFTn",
    "zEbBU7hW",
    "81ATuMgH",
    "Sxr6PZoF",
    "tkOAUp3H",
    "dwT82EF2",
    "xg5LmzbF",
    "xDAsslfn",
    "TFX89e3X",
    "crhB5SvR",
    "460NC0u0",
  ],
  divisionP: [
    "kp5wEQ5A",
    "0Xzq77Er",
    "lHgmZI3O",
    "uDt6lQZA",
    "rRzrhuSz",
    "AEClOTV3",
    "abce1EcZ",
    "GtprLv64",
    "HEpc7EtJ",
    "TQ420oPm",
    "E3TknVzP",
    "R0oFXRKY",
    "nTRSUihj",
    "dlHWL8uG",
    "PhDEKvFP",
    "Fwiv9xd9",
    "vfzwntxO",
    "6x9UHArN",
    "z3uHENr8",
    "AZaAhdzz",
    "BgEStNmc",
    "Xf6avtMr",
    "OLfAOmD2",
    "ym4pz6zl",
    "EA4QaUkS",
    "IOpo95lE",
    "2V8WgwsS",
    "isIVaBRs",
    "pxQ8A9UH",
    "fgbkg0bR",
    "IrOcJWal",
    "UWz2abVN",
    "cKYIbJNR",
    "EQ7dLFRX",
    "fM63d23J",
    "kiHDkzUT",
    "L49aRJ8l",
    "dRcPhm4c",
    "IBqzF8oR",
    "fJqlTEAl",
    "nmjBn8mv",
    "b3b6F2cu",
    "gHQyIJEJ",
    "rBu1NWOO",
    "P89xwCSz",
    "0fnDTKPT",
    "e5mz39an",
    "sF6VePSo",
    "rSvKwzPC",
    "xOr4t5BO",
    "JKH7bquw",
    "odpujLSt",
    "ShDXcq2v",
    "ebUrtIGM",
    "tIdAz5rG",
    "1obVN9By",
    "1T6W3VOw",
  ],
  superfinal: [
    "RSIGxDYD", // Round 1
  ],
};

export const roundChesck = (roundId, eventName) => {
  let roundLeague;
  if (eventName.includes("entrance")) {
    if (eventName.includes("tiebreak"))
      roundLeague = Rounds.entrance[Rounds.entrance.length - 1];
    else roundLeague = Rounds.entrance[roundId];
  } else if (eventName.includes("league 2")) {
    if (eventName.includes("tiebreak"))
      roundLeague = Rounds.league2[Rounds.league2.length - 1];
    roundLeague = Rounds.league2[roundId];
  } else if (eventName.includes("league 1")) {
    if (eventName.includes("tiebreak"))
      roundLeague = Rounds.league1[Rounds.league1.length - 1];
    roundLeague = Rounds.league1[roundId];
  } else if (eventName.includes("division")) {
    if (eventName.includes("tiebreak"))
      roundLeague = Rounds.divisionP[Rounds.divisionP.length - 1];
    roundLeague = Rounds.divisionP[roundId];
  } else if (eventName.includes("superfinal")) {
    if (roundId <= 100) roundLeague = Rounds.superfinal[0];
    //else roundLeague = Rounds.superfinal[1];
  }
  return roundLeague;
};
