const Rounds = {
  playoff3: [
    "J4GNxvcF",
    "3VdvuNss",
    "EwkPBTp6",
    "uR2GPAdT",
    "ZT9ZLlzW",
    "C5kkQn7y",
    "fJhzAr3h",
    "bi58voAJ",
    "ZKX0LPdp",
    "hbcJpbPs",
    "bjCCAqWC",
    "BU7aqpmC",
    "eSachP88",
    "6IfdrB6E",
    "9Zgkc3yB",
    "dAQUeWrA",
    "ReLVXlbo",
    "nuKF1V8q",
    "Oaox7eZr",
    "PklcFd2Z",
    "5yfZ8qjk",
    "xJfXf4g7",
    "VPr0jfPc",
    "aDM1CjUO",
    "wWAAztOw",
    "KX6Pfwn5",
    "aXn9ps6g",
    "Ismc1zTJ",
    "jXP27WtT",
    "gAjUOOnA",
    "F7wdQkK6",
    "eUZriyL1",
    "JlwrcuZl",
    "jGHM8j7x",
    "kY8mTAhg",
    "2o95IncA",
  ],
  playoff2: [
    "krFyT1WL",
    "qU6NccrQ",
    "kpvIyyxf",
    "xUvuO3az",
    "sUK4862S",
    "J01j1BQO",
    "SNAzGYMq",
    "o4U9NAvG",
    "w0hsuEtE",
    "3zgID1xa",
    "bXJmo8ql",
    "7rBgfW5Q",
    "JQ8z5vuV",
    "ZgPYsEYd",
    "xBc9NWCI",
    "fpt2YWTb",
    "MOSOgvij",
    "u3zd02lW",
    "ybGO3A5g",
    "CmmNJnP8",
    "IcqwlJLK",
    "2AI0bcCX",
    "EjMp9x8d",
    "tL3c3Q0u",
    "35iFgGZv",
    "w6WFsA9a",
    "yODOYWle",
    "DmQ4jRGi",
    "Lil8xIut",
    "X3iiBVQx",
    "kGvS3Ilt",
    "GvfZKw8E",
    "eL09mnlp",
    "hT2FptEE",
    "VH9GnsjT",
    "HGYmhHUd",
  ],
  playoff1: [
    "HbrtRVUA",
    "tdsR6WRO",
    "Xyb4gDNy",
    "YIBAJBht",
    "4KGLv8CK",
    "hbYsTGig",
    "3b5o1LTu",
    "tDVMi0dh",
    "mXgvD32o",
    "rQ3YAkwA",
    "ny3TqwDv",
    "VMzmTgEG",
    "nlyXzUU0",
    "01ikfVEW",
    "qEKiZoyZ",
    "nGiV3gnz",
    "fHUfUdDc",
    "Dlcxle1G",
    "aHwF9q2X",
    "BKuVE7OW",
    "Kp3WjXWM",
    "r8nhVe7J",
  ],
  swiss: [
    "x0WJH0Nv",
    "peBGxUpe",
    "xl48cdw2",
    "NJmjEEd8",
    "NoslpRoK",
    "2tAQzVNv",
    "4SfecDRU",
    "G8HTfiE7",
    "boX4IfA2",
    "6MruaXBX",
    "ckNT0yqu",
  ],
  tiebreak: ["xXmZwEl5"],
};

export const roundChesck = (roundId, eventName) => {
  const tcecSeason = "TCEC Season 29 - ";
  let roundLeague;
  if (eventName === (tcecSeason + "Category 3 Playoff").toLowerCase())
    roundLeague = Rounds.playoff3[roundId];
  else if (eventName === (tcecSeason + "Category 2 Playoff").toLowerCase())
    roundLeague = Rounds.playoff2[roundId];
  else if (eventName === (tcecSeason + "Category 1 Playoff").toLowerCase())
    roundLeague = Rounds.playoff1[roundId];
  else if (eventName === (tcecSeason + "Swiss 9").toLowerCase())
    roundLeague = Rounds.swiss[roundId];
  else if (
    eventName.includes("Tiebreak".toLowerCase()) &&
    eventName.includes(tcecSeason.toLowerCase())
  )
    roundLeague = Rounds.tiebreak[0];

  return roundLeague;
};
